version: "3.9"
services:
  superkart-backend:
    build: ./backend_files
    container_name: superkart-backend
    ports:
      - "7860:7860"
    restart: unless-stopped

  superkart-frontend:
    build: ./frontend_files
    container_name: superkart-frontend
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://superkart-backend:7860
    depends_on:
      - superkart-backend
    restart: unless-stopped
